#ifndef _ENUMMODULE_
#define _ENUMMODULE_

enum ClientAddress
{
    VA_GAMEBASE,
    VA_SCENEBASE,
    VA_ACTORBASE,
    VA_ZONETABLE,
    VA_CMDTABLE,
    VA_ACTORCLASSNAMETABLE,
    VA_WS2SEND,
    VA_WS2RECV,
    VA_PACKETLENGTHCONTAINER,
    //VA_STATE_AURA,
    VA_STATE_WI,
    VA_STATE_SH,
    VA_STATE_BM,
    VA_STATE_BMINPUT,
    VC_GETNETBASE,
    VC_DRAWTEXT,
    VC_GETMSGSTR,
    VC_GETOWNCLASSINDEX,
    VC_GETSKILLNAME,
    VC_GETPACKETLENGTH,
    CLADDR_ENUM_MAX,
};

enum ClientDefaultCommand
{
    CMD_WI,
    CMD_SH,
    CMD_AURA,
    CLCMD_ENUM_MAX,
};

#endif  // _ENUMMODULE_
