#ifndef DEFINE_PACKET_H
#define DEFINE_PACKET_H


// packet’è‹`

enum cl_packet
{
	PACKET_CA_REQ_AUTH=0x0064,
	PACKET_CC_REQ_CONNECT,
	PACKET_CC_REQ_SELECT,
	PACKET_CC_REQ_MAKING,
	PACKET_CC_REQ_DELETE,
	PACKET_AC_AUTH_SUCCEEDED,
	PACKET_AC_AUTH_FAILED,
	PACKET_CC_CONNECT_SUCCEEDED,
	PACKET_CC_SELECT_FAILED,
	PACKET_CC_MAKING_SUCCEEDED,
	PACKET_CC_MAKING_FAILED,
	PACKET_CC_DELETE_SUCCEEDED,
	PACKET_CC_DELETE_FAILED,			// 0x0070
	PACKET_CC_SELECT_SUCCEEDED,
	PACKET_CZ_REQ_CONNECT,
	PACKET_ZC_CONNECT_SUCCEEDED,

	PACKET_CZ_LOADING=0x007D,
	PACKET_CZ_TICKCOUNT,
	PACKET_ZC_TICKCOUNT,
	PACKET_ZC_DELETE_OBJECT,			// 0x0080
	PACKET_ZC_BANNED,

	PACKET_CZ_CHAT_NORMAL=0x008C,
	PACKET_ZC_CHAT_NORMAL,
	PACKET_ZC_CHAT_NORMAL_OWN,
	PACKET_UN_008F,
	PACKET_CZ_REQ_NPC,					// 0x0090
	PACKET_ZC_CHANGE_MAP,
	PACKET_ZC_CHANGE_MAP_WITH_ZONE,
	PACKET_UN_0093,
	PACKET_CZ_REQ_NAME,
	PACKET_ZC_RESULT_NAME,
	PACKET_CZ_WHISPER,
	PACKET_ZC_WHISPER,
	PACKET_ZC_WHIPER_RESULT,
	PACKET_CZ_BROADCAST,
	PACKET_ZC_BROADCAST,

	PACKET_ZC_UPDATE_STATUS1=0x00B0,	// 0x00B0
	PACKET_ZC_UPDATE_STATUS2,
	PACKET_CZ_REQ_RESTART,
	PACKET_ZC_RESULT_RESTART,
	PACKET_ZC_NPC_MESSAGE,
	PACKET_ZC_NPC_SHOWN_NEXT,
	PACKET_ZC_NPC_SHOWN_CLOSE,
	PACKET_ZC_NPC_SELECTION,
	PACKET_CZ_NPC_RESULT_SELECTION,
	PACKET_CZ_NPC_RESULT_NEXT,

	PACKET_CZ_CHAT_REQ_MAKING=0x00D5,
	PACKET_ZC_CHAT_RESULT_MAKING,
	PACKET_ZC_CHAT_UPDATE,
	PACKET_ZC_CHAT_DELETE,
	PACKET_CZ_CHAT_REQ_JOIN,
	PACKET_ZC_CHAT_RESULT_JOIN,
	PACKET_ZC_CHAT_UPDATE_MEMBER,
	PACKET_ZC_CHAT_JOIN_MEMBER,
	PACKET_ZC_CHAT_LEAVE_MEMBER,
	PACKET_CZ_CHAT_REQ_CHANGE,
	PACKET_ZC_CHAT_UPDATE_IN,
	PACKET_CZ_CHAT_REQ_CHANGE_OWNER,	// 0X00E0
	PACKET_ZC_CHAT_UPDATE_OWNER,
	PACKET_CZ_CHAT_REQ_KICK,
	PACKET_CZ_CHAT_REQ_LEAVE,
	PACKET_CZ_TRADING_REQ,
	PACKET_ZC_TRADING_REQ,
	PACKET_CZ_TRADING_RESULT,
	PACKET_ZC_TRADING_RESULT,
	PACKET_CZ_TRADING_REQ_ADD,
	PACKET_ZC_TRADING_ADD,
	PACKET_ZC_TRADING_RESULT_ADD,
	PACKET_CZ_TRADING_FIN,
	PACKET_ZC_TRADING_FIN,
	PACKET_CZ_TRADING_CANCEL,
	PACKET_ZC_TRADING_CANCEL,
	PACKET_CZ_TRADING_ACCEPT,
	PACKET_ZC_TRADING_COMPLETE,			// 0X00F0

	PACKET_CZ_CHAT_PARTY=0x0108,
	PACKET_ZC_CHAT_PARTY,

	PACKET_ZC_SHOWN_MVP=0x010D,

	PACKET_ZC_CHANGE_OPTION=0x0119,

	PACKET_CZ_CHAT_GUILD=0x017E,
	PACKET_ZC_CHAT_GUILD,

	PACKET_ZC_TALKIE_MSG=0x0191,

	PACKET_ZC_CHANGE_CONDITION=0x0196,

	PACKET_ZC_LOCALBROADCAST=0x01C3,

	PACKET_CA_REQ_KEY=0x01DB,
	PACKET_AC_RESULT_KEY,
	PACKET_CA_REQ_AUTH_MD5,

	PACKET_CA_CLIENT_ACCOUNT=0x0200,
	PACKET_CA_CLIENT_MD5=0x0204,

	PACKET_ZC_CHANGE_OPTION2=0x0229,
};


#endif	// #ifndef DEFINE_PACKET_H
