#ifndef RAGDEFINE_H_2D9A573A_29D2_4d2b_932F_5D97B39A32D0
#define RAGDEFINE_H_2D9A573A_29D2_4d2b_932F_5D97B39A32D0


// packet

enum packet_ragnarok
{
	PACKET_CA_REQ_AUTH=0x0064,
	PACKET_CC_REQ_CONNECT,
	PACKET_CC_REQ_SELECT,
	PACKET_CC_REQ_MAKING,
	PACKET_CC_REQ_DELETE,
	PACKET_AC_AUTH_SUCCEEDED,
	PACKET_AC_AUTH_FAILED,
	PACKET_CC_CONNECT_SUCCEEDED,
	PACKET_CC_SELECT_FAILED,
	PACKET_CC_MAKING_SUCCEEDED,
	PACKET_CC_MAKING_FAILED,
	PACKET_CC_DELETE_SUCCEEDED,
	PACKET_CC_DELETE_FAILED,			// 0x0070
	PACKET_CC_SELECT_SUCCEEDED,
	PACKET_CZ_REQ_CONNECT,
	PACKET_ZC_CONNECT_SUCCEEDED,

	PACKET_CZ_LOADING=0x007D,
	PACKET_CZ_TICKCOUNT,
	PACKET_ZC_TICKCOUNT,
	PACKET_ZC_DELETE_OBJECT,			// 0x0080
	PACKET_ZC_BANNED,

	PACKET_CZ_CHAT_NORMAL=0x008C,
	PACKET_ZC_CHAT_NORMAL,
	PACKET_ZC_CHAT_NORMAL_OWN,
	PACKET_UN_008F,
	PACKET_CZ_REQ_NPC,					// 0x0090
	PACKET_ZC_CHANGE_MAP,
	PACKET_ZC_CHANGE_MAP_WITH_ZONE,
	PACKET_UN_0093,
	PACKET_CZ_NAME_REQ,
	PACKET_ZC_NAME_RESULT,
	PACKET_CZ_WHISPER,
	PACKET_ZC_WHISPER,
	PACKET_ZC_WHIPER_RESULT,
	PACKET_CZ_BROADCAST,
	PACKET_ZC_BROADCAST,

	PACKET_ZC_UPDATE_STATUS1=0x00B0,	// 0x00B0
	PACKET_ZC_UPDATE_STATUS2,
	PACKET_CZ_REQ_RESTART,
	PACKET_ZC_RESULT_RESTART,
	PACKET_ZC_NPC_MESSAGE,
	PACKET_ZC_NPC_SHOWN_NEXT,
	PACKET_ZC_NPC_SHOWN_CLOSE,
	PACKET_ZC_NPC_SELECTION,
	PACKET_CZ_NPC_RESULT_SELECTION,
	PACKET_CZ_NPC_RESULT_NEXT,
	PACKET_UN_00BA,
	PACKET_CZ_STATUSUP_REQ,
	PACKET_ZC_STATUSUP_RESULT,

	PACKET_CZ_REQ_ACTORACOUNT=0x00C1,
	PACKET_ZC_ACTORCOUNT,

	PACKET_CZ_CHAT_REQ_MAKING=0x00D5,
	PACKET_ZC_CHAT_RESULT_MAKING,
	PACKET_ZC_CHAT_UPDATE,
	PACKET_ZC_CHAT_DELETE,
	PACKET_CZ_CHAT_REQ_JOIN,
	PACKET_ZC_CHAT_RESULT_JOIN,
	PACKET_ZC_CHAT_UPDATE_MEMBER,
	PACKET_ZC_CHAT_JOIN_MEMBER,
	PACKET_ZC_CHAT_LEAVE_MEMBER,
	PACKET_CZ_CHAT_REQ_CHANGE,
	PACKET_ZC_CHAT_UPDATE_IN,
	PACKET_CZ_CHAT_REQ_CHANGE_OWNER,	// 0X00E0
	PACKET_ZC_CHAT_UPDATE_OWNER,
	PACKET_CZ_CHAT_REQ_KICK,
	PACKET_CZ_CHAT_REQ_LEAVE,
	PACKET_CZ_TRADING_REQ,
	PACKET_ZC_TRADING_REQ,
	PACKET_CZ_TRADING_RESULT,
	PACKET_ZC_TRADING_RESULT,
	PACKET_CZ_TRADING_REQ_ADD,
	PACKET_ZC_TRADING_ADD,
	PACKET_ZC_TRADING_RESULT_ADD,
	PACKET_CZ_TRADING_FIN,
	PACKET_ZC_TRADING_FIN,
	PACKET_CZ_TRADING_CANCEL,
	PACKET_ZC_TRADING_CANCEL,
	PACKET_CZ_TRADING_ACCEPT,
	PACKET_ZC_TRADING_COMPLETE,			// 0X00F0

	PACKET_CZ_PARTY_CREATE=0x00F9,
	PACKET_ZC_PARTY_CREATE_RESULT,
	PACKET_ZC_PARTY_INFO,
	PACKET_CZ_PARTY_INVITE,
	PACKET_ZC_PARTY_INVITE_RESULT,
	PACKET_ZC_PARTY_INVITE,
	PACKET_CZ_PARTY_INVITE_RESULT,
	PACKET_CZ_PARTY_LEAVE,

	PACKET_CZ_CHAT_PARTY=0x0108,
	PACKET_ZC_CHAT_PARTY,

	PACKET_ZC_SHOWN_MVP=0x010C,
	PACKET_UN_010D,
	PACKET_ZC_SKILLINFO_UPDATE,
	PACKET_ZC_SKILLINFO_ALL,
	PACKET_ZC_SKILL_USE_RESULT,
	PACKET_ZC_SKILLINFO,
	PACKET_CZ_SKILLUP_REQ,
	PACKET_CZ_SKILL_USE,

	PACKET_ZC_CHANGE_OPTION=0x0119,

	PACKET_CZ_CHAT_GUILD=0x017E,
	PACKET_ZC_CHAT_GUILD,

	PACKET_ZC_TALKIE_MSG=0x0191,
	PACKET_ZC_CHANGE_CONDITION=0x0196,
	PACKET_CZ_GM_HIDE=0x019D,
	PACKET_ZC_LOCALBROADCAST=0x01C3,
	PACKET_ZC_NOTICE_USEITEM=0x01C8,

	PACKET_ZC_ADD_ACTOR1=0x01D8,
	PACKET_ZC_ADD_ACTOR2,
	PACKET_ZC_MOV_ACTOR,

	PACKET_CA_REQ_KEY=0x01DB,
	PACKET_AC_RESULT_KEY,
	PACKET_CA_REQ_AUTH_MD5,

	PACKET_CA_CLIENT_ACCOUNT=0x0200,
	PACKET_CA_CLIENT_MD5=0x0204,

	PACKET_CZ_RANK_REQ_BS=0x0217,
	PACKET_CZ_RANK_REQ_AM,
	PACKET_ZC_RANK_BS,
	PACKET_ZC_RANK_AM,

	PACKET_ZC_CHANGE_OPTION_NEW=0x0229,
};


// condition

enum condition_info
{
	CI_NONE=0xFFFF,

	CI_HALLUCINATION=0x0022,	// NPC_HALLUCINATION
	CI_ELEMENTALCONV=0x0040,	// SA_ELEMENT???
	CI_ELEMENT_FIRE=0x005A,		// SA_FLAMELAUNCHER
	CI_ELEMENT_WATER,			// SA_FROSTWEAPON
	CI_ELEMENT_WIND,			// SA_LIGHTNINGLOADER
	CI_ELEMENT_GROUND,			// SA_SEISMICWEAPON
	CI_BERSERK=0x006B,			// LK_BERSERK
	CI_ASSUMPTIO=0x006E,		// HP_ASSUMPTIO
	CI_MAGICPOWER=0x0071,		// HW_MAGICPOWER
	CI_ELEMENT_SHADOW=0x0092,	// TK_SEVENWIND
	CI_ELEMENT_GHOST=0x0094,	// TK_SEVENWIND
	CI_SOULLINK,				// SL_???
	CI_KAITE=0x0099,			// SL_KAITE
	CI_KAUPE=0x009E,			// SL_KAUPE
	CI_TRUESIGHT=0x00B8,		// ???
	CI_CLOSECONFINE_OWN=0x00C8,	// RG_CLOSECONFINE
	CI_CLOSECONFINE_TGT,		// RG_CLOSECONFINE
};


#endif	// #ifndef RAGDEFINE_H
